# Generated by Django 5.1 on 2024-11-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('pant', 'pant'), ('Saree', 'Saree'), ('Kurta', 'Kurta'), ('Gown', 'Gown')], max_length=100),
        ),
    ]
